CREATE OR REPLACE FUNCTION pieces_lsh1(INTEGER[])
RETURNS TABLE(band INTEGER, minisign INTEGER[]) AS $$
BEGIN
	FOR i IN 0..19
	LOOP
		RETURN QUERY SELECT i, $1[i*5+1:i*5+5];
	END LOOP;
	RETURN;
END
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION get_lsh1(INTEGER[])
RETURNS TABLE(id INTEGER) AS $$
BEGIN
	RETURN QUERY SELECT DISTINCT code FROM lsh1 NATURAL JOIN pieces_lsh1($1);
	RETURN;
END $$ LANGUAGE plpgsql IMMUTABLE;
